sudo: required
services:
- docker
before_script:
- chmod +x $TRAVIS_BUILD_DIR/build.sh
- chmod +x $TRAVIS_BUILD_DIR/distribute.sh
script:
- $TRAVIS_BUILD_DIR/build.sh
after_success:
- $TRAVIS_BUILD_DIR/distribute.sh
env:
  global:
    secure: YYbON8erb/7UJZ6iFXXU1a2GMsYv8SBgYsrixxoGV955VFhlIuzpt8vxE4hXIYUFstAVDvHm32SXDoXi5UrJCh25S30ULvtJt7kJMjLG9rUyL4ZKMITL8Bc0qoRqOg2BJk+IDo7qESOBoU42Ge4C8jzFdXlOclracLgyziMsN1VYOuHhVJbTSd2iX4M0d7Gy7tupQzy81B6VpFwaVLwamLN65lHRgJMOeWy4o6gVZHCZmAAqXSiYw739t57N6yTDHEGFNpiPYcPzkihdOCM63OLY/hkKB699WQm1J0PjhEhyR2j4Njffzb4tMGT/jJ6U/bJcQgHjBx8qhWYzuTY6fjn7aWvBXOi+fm9EyIgMcneqhTktP/fCBrjVDdqAlA/HERgvbPrZ34ShupXhMXCkyY5Tn2OQzDLZUEPYiVj5BBg+xRL39WMcJFRtHFVXNihrAbuwGJyN6J2yGhOqfcgDis+tcMGYQeelkG8SgEEHCPUXZgteyF9EtZEX9pECDiomyMx5JfJRsokcxuGptHxw+rh7tWj8EGXC25F5Yn9pMm1rF3QD/jfn6psn86XYTI6f4BegmkIq7ezql8YmDIw28FiUtoNbLsjlrKeQkrnNmyP6atIDTN0J/rOw1yVzTCu7rDj/poNgq6hFjDnpVxlk53RfxLGM3cjNIePSMeRvib0=
notifications:
  slack:
    secure: LZ0xi0vdrDdxEKqIUKSuEoOh4NhOiX5JWGAKfRr2+xdGHHPTSJHhtqvJHskhypvF9sfWJf/6VDEmvQ1kzlPiAavHedmf32yJswN6sQGL90urB0cgyFAKNLSJtcbzuCBfx6bvUJkASi2KQQt198TGZiKWIPQoCrQy5DHRD40AvuGzVAtvyDA1hlQzUET/+qTa50LMsGfEY5O6GDLU2Ye5iz5LZLY+yui1gpml3tQ+forjbvk3Xlv7HonhCN/7TImuesSMf6ZIwatwfzBEAN9257XyU71sSUCi9XzBIr81OMYjS6qn3Ss3mMjRzi8y5J5FvFm0/Dgs6O5N5FFTn78N4evsCVtWtWZ0K8Ar2ZnQN422ZtbjpUTjtMAyVwkAFKnMYbBv3BJlSmJTET1W42Ahr1f55Fv2wAeaocVTJgs2B5VIf8oq/WUIoxJyFbmQtLXvpqBsuAg40N/OegyIUYyBUm1SXjd1xyNmC7NXI0IyYgGNCkRx0e6bZ3xQPt2DIfa9GWtKhs+Wyd9gJn3U4hK6I//cgofBjJNDMiQD/KLbfpTyJLkZWz6vtQtl4krVDV3TIhZqNWTrllo6/VQfkhcqZfUfK8vlbBRjNanVu7WIe81EQyKrqrpvG+wxp9Pv2q8iJYWX2m0xUtn/7hOrowHDMLrfmNczJu8fm/dCRvYxKqQ=
